name: Remote Server Git Pull

on:
  workflow_dispatch:

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 185.219.239.3
          username: boldstme
          password: ${{ secrets.PASS }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.BOLD_KEY }}
          script: whoami
